#! /bin/bash
if [ "$SUDO_USER" == "" ]; then
  echo "SUDO_USER is not defined. You must run this script as superuser:"
  echo '  sudo ./build'
  exit -1
fi
echo building FirePiCam...
if [ ! -e /opt/vc/userland ]
then
	echo installing cmake...
	apt-get install cmake
	echo installing userland header files...
	git clone git://github.com/raspberrypi/userland.git /opt/vc/userland
fi
rm -rf CMakeFiles CMakeFiles.txt *.cmake CMakeCache.txt
cmake -DCMAKE_INSTALL_PREFIX=/usr .
make install
